version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ecommerce_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mvp-marketplace-services:
    build: ../mvp-marketplace-services
    container_name: mvp-marketplace-services
    volumes:
      - ../mvp-marketplace-services:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - FAKESTORE_URL=https://fakestoreapi.com
      - VIACEP_URL=https://viacep.com.br/ws
    command: npm run dev

  mvp-marketplace-api:
    build: ../mvp-marketplace-api
    container_name: mvp-marketplace-api
    volumes:
      - ../mvp-marketplace-api:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ecommerce_db?schema=public
      - SECONDARY_API_URL=http://mvp-marketplace-services:3002
      - PORT=3001
    depends_on:
      db:
        condition: service_healthy
      mvp-marketplace-services:
        condition: service_started
    command: >
      sh -c "npx prisma db push && npm run dev"

  mvp-front-marketplace:
    build: .
    container_name: mvp-front-marketplace
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - mvp-marketplace-api

volumes:
  postgres_data:
